# mihomo é…ç½®
# æ—¥æœŸï¼š2025-11-08 00:21:37
# é…ç½®ä½œè€…ï¼šhttps://t.me/iKeLee
# é€‚ç”¨ç‰ˆæœ¬ï¼šæ‰€æœ‰ä½¿ç”¨ mihomo æ ¸å¿ƒçš„ç¨‹åº
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894

unified-delay: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: true
udp: true

external-controller: 0.0.0.0:9090
# external-ui: ui
# external-ui-url: 'https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'

geox-url:
  # geoip: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat'
  # geosite: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat'
  mmdb: 'https://geodata.kelee.one/Country-Masaiki.mmdb'
  asn: 'https://geodata.kelee.one/GeoLite2-ASN-P3TERX.mmdb'

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com

  skip-domain:
    - Mijia Cloud

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

# P2Pä¸‹è½½ç«¯å£
listeners:
- name: socks5-in-1
  type: socks
  port: 10808
  listen: 0.0.0.0
  udp: true
  users: []
  proxy: DIRECT

dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - +.lan
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query

# é”šç‚¹ - èŠ‚ç‚¹è®¢é˜…çš„å‚æ•° [æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡è®¢é˜…èŠ‚ç‚¹ï¼Œæ¯ 6 ç§’ä¸€æ¬¡å¥åº·æ£€æŸ¥]
NodeParam: &NodeParam {type: http, interval: 3600, health-check: {enable: true, url: 'http://www.google.com/blank.html', interval: 6}}

# é”šç‚¹ - èŠ‚ç‚¹è®¢é˜…
proxy-providers: 
  æœºåœºåç§°1:
    url: 'æœºåœº1çš„è®¢é˜…URL'
    <<: *NodeParam
    path: './proxy_providers/æœºåœºåç§°1.yaml'
    override:
      additional-prefix: "[æœºåœºåç§°1] " # ä¸ºè®¢é˜…èŠ‚ç‚¹æ·»åŠ æœºåœºåç§°å‰ç¼€
  æœºåœºåç§°2:
    url: 'æœºåœº2çš„è®¢é˜…URL'
    <<: *NodeParam
    path: './proxy_providers/æœºåœºåç§°2.yaml'
    override:
      additional-prefix: "[æœºåœºåç§°2] " # ä¸ºè®¢é˜…èŠ‚ç‚¹æ·»åŠ æœºåœºåç§°å‰ç¼€

# é”šç‚¹ - èŠ‚ç‚¹ç­›é€‰ç»„
FilterHK: &FilterHK '^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|HKG|Hong)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterTW: &FilterTW '^(?=.*((?i)ğŸ‡¹ğŸ‡¼|å°æ¹¾|(\b(TW|TWN|Tai|Taiwan)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterJP: &FilterJP '^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|JPN|Japan)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterKR: &FilterKR '^(?=.*((?i)ğŸ‡°ğŸ‡·|éŸ©å›½|éŸ“|é¦–å°”|(\b(KR|KOR|Korea)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterSG: &FilterSG '^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|SGP|Singapore)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterUS: &FilterUS '^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|USA|United States)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterUK: &FilterUK '^(?=.*((?i)ğŸ‡¬ğŸ‡§|è‹±å›½|ä¼¦æ•¦|(\b(UK|GBR|United Kingdom)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterFR: &FilterFR '^(?=.*((?i)ğŸ‡«ğŸ‡·|æ³•å›½|(\b(FR|FRA|France)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterDE: &FilterDE '^(?=.*((?i)ğŸ‡©ğŸ‡ª|å¾·å›½|(\b(DE|DEU|Germany)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterGame: &FilterGame '^(?=.*((?i)æ¸¸æˆ|ğŸ®|(\b(GAME)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­)).*$'
FilterAll: &FilterAll '^(?=.*(.))(?!.*((?i)ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|è¶…æ—¶|æ”¶è—|ç¦åˆ©|é‚€è¯·|å¥½å‹|å¤±è”|(\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|Traffic)(\d+)?\b|(\d{4}-\d{2}-\d{2}|\dG)))).*$'

# ç­–ç•¥ç»„å‚æ•°é”šç‚¹
# é”šç‚¹ - æ—¶å»¶ä¼˜é€‰å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œå®¹å·® 20msï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
UrlTest: &UrlTest {type: url-test, interval: 6, tolerance: 20, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - æ•…éšœè½¬ç§»å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
FallBack: &FallBack {type: fallback, interval: 6, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - è´Ÿè½½å‡è¡¡å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
LoadBalance: &LoadBalance {type: load-balance, interval: 6, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, strategy: consistent-hashing, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - è§„åˆ™å‚æ•° [æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡è®¢é˜…è§„åˆ™ï¼Œæ›´æ–°è§„åˆ™æ—¶ä½¿ç”¨ç›´è¿ç­–ç•¥]
RuleProviders: &RuleProviders {type: http, behavior: classical, interval: 3600, format: yaml, proxy: DIRECT}

# ç­–ç•¥ç»„
proxy-groups: 
  - {name: æ¸¸æˆé€‰æ‹©, type: select, include-all-providers: true, filter: *FilterGame, proxies: [DIRECT, å…¨çƒé€‰æ‹©]}
  - {name: å…¨çƒé€‰æ‹©, type: select, include-all-providers: true, filter: *FilterAll}
  - {name: å¢ƒå¤–ä¸‹è½½, type: select, include-all-providers: true, filter: *FilterAll, proxies: [DIRECT]}
  - {name: AI, type: select, include-all-providers: true, filter: *FilterAll}
  - {name: TikTok, type: select, include-all-providers: true, filter: *FilterAll}
  - {name: SpeedtestIntl, type: select, include-all-providers: true, filter: *FilterAll, proxies: [DIRECT]}
  - {name: App Store, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: Appleè´¦æˆ·, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: TestFlight, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: 1Password, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: Netflix, type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: Emby, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: å…œåº•åå¤‡ç­–ç•¥, type: fallback, proxies: [é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}

  - {name: é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterHK}
  - {name: å°æ¹¾è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterTW}
  - {name: æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterJP}
  - {name: éŸ©å›½è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterKR}
  - {name: æ–°å›½è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterSG}
  - {name: ç¾å›½è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterUS}
  - {name: è‹±å›½è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterUK}
  - {name: æ³•å›½è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterFR}
  - {name: å¾·å›½è‡ªåŠ¨ç­–ç•¥, <<: *UrlTest, filter: *FilterDE}

# è®¢é˜…è§„åˆ™
rule-providers:
  LAN:
    <<: *RuleProviders
    path: './rules/Lan.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/LAN_SPLITTER.yaml'

  Direct:
    <<: *RuleProviders
    path: './rules/Direct.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Direct.yaml'

  Proxy:
    <<: *RuleProviders
    path: './rules/Proxy.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Proxy.yaml'

  ChinaDownloadCDN:
    <<: *RuleProviders
    path: './rules/ChinaDownloadCDN.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/ChinaDownloadCDN.yaml'

  InternationalDownloadCDN:
    <<: *RuleProviders
    path: './rules/InternationalDownloadCDN.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/InternationalDownloadCDN.yaml'

  AI:
    <<: *RuleProviders
    path: './rules/AI.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AI.yaml'

  TikTok:
    <<: *RuleProviders
    path: './rules/TikTok.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/TikTok.yaml'

  SpeedtestIntl:
    <<: *RuleProviders
    path: './rules/SpeedtestInternational.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/SpeedtestInternational.yaml'

  Game:
    <<: *RuleProviders
    path: './rules/Game.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Game.yaml'

  1Password:
    <<: *RuleProviders
    path: './rules/1PasswordUS.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/1PasswordUS.yaml'

  Steam:
    <<: *RuleProviders
    path: './rules/Steam.yaml'
    url: 'https://rule.kelee.one/Clash/Steam.yaml'

  Netflix:
    <<: *RuleProviders
    path: './rules/Netflix.yaml'
    url: 'https://rule.kelee.one/Clash/Netflix.yaml'

  Emby:
    <<: *RuleProviders
    path: './rules/Emby.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/EmbyServer.yaml'

  iCloudChina:
    <<: *RuleProviders
    path: './rules/iCloudChina.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/iCloudChina.yaml'

  ApplePushNotificationService:
    <<: *RuleProviders
    path: './rules/ApplePushNotificationService.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/ApplePushNotificationService.yaml'

  AppleSoftwareUpdates:
    <<: *RuleProviders
    path: './rules/AppleSoftwareUpdates.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AppleSoftwareUpdates.yaml'

  AppleID:
    <<: *RuleProviders
    path: './rules/AppleID.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AppleAccount.yaml'

  AppStore:
    <<: *RuleProviders
    path: './rules/AppStore.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AppStore.yaml'

  TestFlight:
    <<: *RuleProviders
    path: './rules/TestFlight.yaml'
    url: 'https://rule.kelee.one/Clash/TestFlight.yaml'

  Microsoft:
    <<: *RuleProviders
    path: './rules/Microsoft.yaml'
    url: 'https://rule.kelee.one/Clash/Microsoft.yaml'

  Google:
    <<: *RuleProviders
    path: './rules/Google.yaml'
    url: 'https://rule.kelee.one/Clash/Google.yaml'

  Telegram:
    <<: *RuleProviders
    path: './rules/Telegram.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Telegram.yaml'

  ESET_China:
    <<: *RuleProviders
    path: './rules/ESET_China.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/ESET_China.yaml'

# è§„åˆ™æŒ‡å‘
rules:
  - RULE-SET, LAN, DIRECT
  - RULE-SET, Direct, DIRECT
  - RULE-SET, Proxy, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, ChinaDownloadCDN, DIRECT
  - RULE-SET, InternationalDownloadCDN, å¢ƒå¤–ä¸‹è½½
  - RULE-SET, AI, AI
  - RULE-SET, TikTok, TikTok
  - RULE-SET, SpeedtestIntl, SpeedtestIntl
  - RULE-SET, Steam, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, Game, æ¸¸æˆé€‰æ‹©
  - RULE-SET, Netflix, Netflix
  - RULE-SET, Emby, Emby
  - RULE-SET, TestFlight, TestFlight
  - RULE-SET, iCloudChina, DIRECT
  - RULE-SET, ApplePushNotificationService, DIRECT
  - RULE-SET, AppleSoftwareUpdates, DIRECT
  - RULE-SET, AppleID, Appleè´¦æˆ·
  - RULE-SET, AppStore, App Store
  - RULE-SET, 1Password, 1Password
  - RULE-SET, Microsoft, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, Google, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, Telegram, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, ESET_China, DIRECT
  - GEOIP, CN, DIRECT
  - MATCH, å…œåº•åå¤‡ç­–ç•¥